language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

env:
  global:
    - PHPCS_STANDARD='vendor/novactive/phpcs-novastandards/src/NovaEZ'

before_install:
  - curl -sS https://getcomposer.org/installer | php -- --quiet

install:
  - php composer.phar install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpcs --standard=$PHPCS_STANDARD src/
  - ./vendor/bin/phpmd src/ text codesize,unusedcode,naming
  - ./vendor/bin/phpcpd src
